# Getting Started {.unnumbered} 

## Install EEGLAB
::: {.callout-important}
## Download and install EEGLAb
[EEGLAB - download the compiled version]( https://eeglab.org/others/Compiled_EEGLAB.html)
:::

Run the installation software and open EEGLAB on your machine. 

If you can’t get it running on your machine, you can use machines in class and speak to staff about support on getting EEGLAB installed on loan machines. 

The Matlab version of EEGLAB is somewhat more stable and there are more features that are available. We haven't used this as it's not completely free and we want what you learn to be available to you after you leave. However, if you want to install Matlab, for now Middlesex provides a liscence, create an account and download Matlab here: 

-  [Matlab Middlesex Licence Version](https://uk.mathworks.com/academia/tah-portal/middlesex-university-599605.html)

Once installed and up and running, you can follow the instructions here on how to get EEGLAB running from within Matlab: 

-  [EEGLAB for Matlab](https://eeglab.org/others/How_to_download_EEGLAB.html)

## Download the data for this tutorial

::: {.callout-important}
## Download the data
[Click here to download the data for this tutorial](https://drive.google.com/uc?export=download&id=1pVrJfJIme5so6SIolbEGHKVmZGNTYMyT)
:::

The data for this tutorial includes data from 6 participants - this isn't the whole data analysed in the @jones2019rhythmic paper but a subset - we think 6 participants is enough for you to get used to analysis and produce a good ERP by the end of the tutorial. 




::: {.callout-warning}
## The file is about 3Gb and may take a while to download. 
:::

Once you've downloaded the file unzip it and extract the containing data. 


## Data format

Each file is named with a participant number e.g., `Participant_03 `. There are 6 participant datasets in total. Each participant has 3 separate files each named the same thing with different file formats: 

-  `.eeg` - the actual EEG data recorded digitally. 
-  `.vhdr` - the 'header' information, this gives us the names and spatial location of the electrodes. 
-  `.vmrk` - this file stores the 'trigger information'; information sent from the experimental computer containing information about when a participant saw a particular stimuli or gave a specific response. 
