project:
  type: book
number-sections: false

book:
  google-analytics: 
    tracking-id: G-GSY6VFHW6X
  favicon: images/icon.ico
  title: EEG Analysis
  author: Jon Silas & Alex Jones
  date: last-modified
  downloads: 
  - pdf
  - docx
  - epub
  sharing:
  - twitter
  - linkedin
  sidebar:
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/JonSilas/EEGanalysis
  chapters:
    - index.qmd
    - part: 01-EEGLAB.qmd
      chapters: 
        - 02-getting_started.qmd
        - 03-import_data.qmd
        - 04-Eye-balling_data.qmd
        - 05-down_sample.qmd
        - 06-filtering.qmd
        - 07-interpolation.qmd
        - 08-re-reference.qmd
        - 09-ICA.qmd
        - 10-artefact_rejection.qmd
        - 11-segmentation.qmd
        - 12-grandaverage.qmd
    - 13-submit.qmd
    - Resources.qmd
    - references.qmd
title-block-banner: "orange" 
title-block-banner-color: "black" 

csl: apa.csl
bibliography: references.bib
toc-title: On this page

format:
  html:
    link-external-newwindow: true
    theme:
      light: flatly
      dark: darkly
    number-sections: false
    css: include/webex.css
    include-after-body: include/webex.js
  pdf:
    documentclass: scrreprt
  epub:
    cover-image: images/logo.jpg
  docx:
    toc: true
editor: source

